### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by marcelaraujo** [faceyspacey/universal-demo#11]
Hi @faceyspacey 

Did you do any bench?

This project is awesome o//

**Comment by faceyspacey** [comment]
Not yet, but the relevant chunk flushing code on the server has become a lot smaller than the `flushModuleIds` original technique. It's basically as fast as it will ever be, and if not, it's primarily one function to modify:

https://github.com/faceyspacey/webpack-flush-chunks/blob/master/src/flushChunks.js#L192

When it first came out in the spring, a lot more work had to be done since we couldn't specify the chunk names Webpack creates. Now we specify the chunk names, and it's not far from keying into a hash to get the files. Before I had to do crazy work to dig through both server and client stats to find the chunks to server. The code still exists in that file but its not being used.

**Comment by faceyspacey** [comment]
I'm gonna close this for now. Hit me on Reactlandia chat if you ever need anything.
