### ISSUE TITLE
Impossibly difficult to implement

### ISSUE THREAD

**Issue by tatsujb** [faceyspacey/universal-demo#15]
This code is impossibly difficult to use.

I'm loosing my mind.

could you not make some sort of guide.

Any attempt to add this into to my already very fleshed-out react-redux app is utterly crazy.

```
"C:\Program Files\JetBrains\WebStorm 2017.2.4\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" start

> product-boundedContext-module-microservice@1.0.0 start 
> cross-env NODE_ENV=development node server/dev.js
"C:\Program Files\JetBrains\WebStorm 2017.2.4\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" start

> product-boundedContext-module-microservice@1.0.0 start 
> cross-env NODE_ENV=development node server/dev.js
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! product-boundedContext-module-microservice@1.0.0 start: `cross-env NODE_ENV=development node server/dev.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the product-boundedContext-module-microservice@1.0.0 start script 'cross-env NODE_ENV=development node server/dev.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the product-boundedContext-module-microservice package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development node server/dev.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs product-boundedContext-module-microservice
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls product-boundedContext-module-microservice
npm ERR! There is likely additional logging output above.

```

this is awful and I can't see the light at the end of the tunnel.

I don't understand how you expect people to be able to integrate this.

make a guide or a video guide or something

**Comment by dawidvdh** [comment]
Hey @tatsujb I can maybe try and help you, I have used @faceyspacey toolset quite a bit and haven't had any issues, however i am going to need a lot more insight as the error message you have provided is a generic npm start script error which doesn't provide any real insight... Is there anyway you could share the code of the project you are working on?

**Comment by pardejini** [comment]
Hi, @dawidvdh I've been having some implementaiton problems too. I'm trying to add a simple api endpoints, but every time I try to import a file to server/index.js webpack seems to disagree with me. Sometimes it works in dev mode other times in prod, I've tried almost everything. Any tips on how to implement api  routes or graphql to this project or even to the base redux-first-router-demo boilerplate?

**Comment by faceyspacey** [comment]
The Redux first router demo has a simple API. So you need to determine what u r doing differently than that.

I would import your code there and remove the stuff from the demo u don't need and simply add to that API.

Eventually we will have a blog demo with a full API FYI. For RFR.

**Comment by faceyspacey** [comment]
The key is to isolate and do as Kittle as possible and incrementally add isolated parts to find which aspect is causing the problem. Like "control" in science class experiments.

**Comment by dawidvdh** [comment]
@pardejini if your problem is simply just including api routes I tested adding:

```javascript
// server/index.js line 18
app.get( '/api/hello', function (req, res) {
  res.send({ hello: 'message' })
} )
```

which worked perfectly fine do keep in mind with this project that the `server/index.js` is not being compiled via babel so if you are trying to import ES6 it probably wont work however you can add compilation of the server relatively easily by precompiling or at runtime using babel.

If that doesn't answer your question I created a boilerplate a little while ago however i haven't had time to fully implement an example of it with redux-first-router although it does utilize all the other tools here is a link with redux-first-router partially implemented madeagency/reactivity/redux-first-router @faceyspacey please do notify me if I am implementing it incorrectly so far, Will try and have the implementation done ASAP.

**Comment by pardejini** [comment]
Thanks @faceyspacey  and @dawidvdh. 😃

**Comment by dawidvdh** [comment]
@pardejini it started when i added `babel-watch` as a `devDependencies`, then its complaining about the css which im sure you can figure out by digging into your build process etc.

**Comment by faceyspacey** [comment]
you can use this babel plugin to handle css modules in babel:

https://github.com/michalkvasnicak/babel-plugin-css-modules-transform

that will generate the class names properly without creating css. u can specify an option in the babel plugin config so that the class names are generated just like in webpack.

**Comment by tatsujb** [comment]
@dawidvdh thanks.
why is it that I can't have ES6?
