### ISSUE TITLE
webpack.run at runtime

### ISSUE THREAD

**Issue by Nicktho** [faceyspacey/universal-demo#24]
Sorry if this is not the appropriate place to ask, but I'm trying to find out why webpack is run at runtime rather than as a build step. Is this just an arbitrary decision or is there something I'm missing out on.

Thanks for all you do @faceyspacey!

**Comment by faceyspacey** [comment]
You can configure a lot more, just check these lines:

https://github.com/faceyspacey/universal-demo/blob/master/server/index.js#L28-L48

In the case of the middleware, they call `run` internally, which is why we listen to the `done` callback.

In production, we get the `stats` from the `run` callback. 

In short, we need callbacks and composability. There's probably a lot of other reasons, but it boils down to doing it in code affords you a lot more flexibility and control.

**Comment by Nicktho** [comment]
I see, thankyou!

**Comment by DannyDane** [comment]
In the universal-demo, you use express.static to serve static assets.
But what would you do if you wanted to serve those assets from a different place, such as NGINX or a CDN?
All the filenames of the assets are only known after you start your app on the deployment server.

Am I missing something?

**Comment by faceyspacey** [comment]
the filenames are known now. you need to change the host prefixed to it. set `clientStats.publicPath` directly prior to calling `flushChunks` :)

and obviously don't host them yourself in `server/index.js` unless you're using something like cloudflare which passes through to your actual server to initially get the assets.
